### ISSUE TITLE
Package published?

### ISSUE THREAD

**Issue by golmansax** [jquense/react-dialogs#1]
Hey, I was curious to try this but I couldn't find the package on NPM.  `react-dialog` is someone else's repo and `react-dialogs` doesn't exist.  Thanks!

**Comment by jquense** [comment]
Hey there. I haven't published this to npm yet but it should be in fine
working order. if you wanted to try it out just list
"jquense/react-dialogs" for the version in your package.json and npm will
pull it directly from github

**Comment by golmansax** [comment]
Thanks, didn't know that!
